[package]
name = "single-project"
version = "0.1.0"
authors = ["Arvid Gerstmann <github@arvid.io>"]
edition = "2024"

[dependencies]

[package.metadata.nfpm]
epoch = "2"
contents = [
    { src = "LICENSE", dst = "/usr/share/licenses/single-project/LICENSE" },
]
