[package]
name = "bin1"
version = "1.0.0"
publish = false

# Inherited.
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
lib1.workspace = true
