[package]
name = "lib1"
version = "0.1.0"
publish = false

# Inherited.
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
